begin;
create temporary table actors(name text primary key,id uuid default gen_random_uuid());
insert into actors(name) values('owner'),('voter'),('third'),('admin'),('moderator');
grant select on actors to anon,authenticated;
insert into auth.users(id,email,raw_user_meta_data) select id,id::text||'@example.invalid','{}'::jsonb from actors;
update public.profiles set role=name::public.profile_role from actors where profiles.id=actors.id and name in ('admin','moderator');
create temporary table taxa(name text primary key,id uuid default gen_random_uuid());
insert into taxa(name) values('sensitive'),('later');
insert into public.species(id,scientific_name,is_sensitive) select id,'test_'||id,name='sensitive' from taxa;
grant select on taxa to anon,authenticated;
create temporary table fixtures(name text primary key,id uuid default gen_random_uuid());
insert into fixtures(name) values('ordinary'),('guess'),('confirm'),('flag'),('private'),('catalog');
grant select on fixtures to anon,authenticated;
insert into public.sightings(id,user_id,latitude,longitude,found_date,geoprivacy,reported_sensitive)
select f.id,a.id,50,14,current_date,case when f.name='private' then 'private' when f.name in ('guess','catalog') then 'open' else 'obscured' end,f.name in ('flag','private')
from fixtures f cross join actors a where a.name='owner';
create function pg_temp.check_it(v boolean,label text) returns void language plpgsql as $$ begin if v is distinct from true then raise exception 'FAIL: %',label; end if; end $$;
create temporary table before_points as select id,public_latitude,public_longitude from public.sightings where id in (select id from fixtures);
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from actors where name='owner'),true);
insert into public.identifications(sighting_id,user_id,species_id) values((select id from fixtures where name='guess'),auth.uid(),(select id from taxa where name='sensitive'));
insert into public.identifications(sighting_id,user_id,species_id) values((select id from fixtures where name='catalog'),auth.uid(),(select id from taxa where name='later'));
select pg_temp.check_it((select id_status='needs_id' and geoprivacy='obscured' and obfuscation_radius_m=3000 from public.sightings where id=(select id from fixtures where name='guess')),'sensitive guess protects before consensus');
select pg_temp.check_it((select latitude=50 and longitude=14 from public.public_sightings where id=(select id from fixtures where name='guess')),'owner exact');
delete from public.identifications where sighting_id=(select id from fixtures where name='guess');
select pg_temp.check_it((select obfuscation_radius_m=3000 from public.sightings where id=(select id from fixtures where name='guess')),'deleting guess does not shrink');
reset role;
update public.sightings set species_id=(select id from taxa where name='sensitive'),id_status='confirmed' where id=(select id from fixtures where name='confirm');
update public.species set is_sensitive=true where id=(select id from taxa where name='later');
select pg_temp.check_it((select bool_and(s.obfuscation_radius_m=3000 and (s.public_latitude,s.public_longitude) is distinct from (b.public_latitude,b.public_longitude)) from public.sightings s join before_points b using(id) where s.id in (select id from fixtures where name in ('guess','confirm','catalog'))),'hint, confirmation and catalogue change recompute existing points');
select pg_temp.check_it((select geoprivacy='private' and obfuscation_radius_m=3000 from public.sightings where id=(select id from fixtures where name='private')),'private stays private');
select pg_temp.check_it((select bool_and(6371008.8*2*asin(sqrt(power(sin(radians(public_latitude-latitude)/2),2)+cos(radians(latitude))*cos(radians(public_latitude))*power(sin(radians(public_longitude-longitude)/2),2))) <= obfuscation_radius_m+0.01) from public.sightings where id in (select id from fixtures)),'all random points within radius');
create temporary table stable_points as select id,public_latitude,public_longitude from public.sightings where id in (select id from fixtures);
update public.sightings set notes='unrelated edit' where id in (select id from fixtures);
select pg_temp.check_it((select bool_and((s.public_latitude,s.public_longitude)=(b.public_latitude,b.public_longitude)) from public.sightings s join stable_points b using(id)),'notes preserve points');
select pg_temp.check_it((select obfuscation_radius_m=100 from public.sightings where id=(select id from fixtures where name='ordinary')),'ordinary stays 100m');
set local role anon;
select set_config('request.jwt.claim.sub','',true);
select pg_temp.check_it((select count(*)=0 from public.public_sightings where id=(select id from fixtures where name='private')),'anon private hidden');
select pg_temp.check_it((select obfuscation_radius_m=3000 and (latitude<>50 or longitude<>14) from public.public_sightings where id=(select id from fixtures where name='confirm')),'anon metadata and fuzzed coordinates');
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from actors where name='moderator'),true);
select pg_temp.check_it((select latitude<>50 or longitude<>14 from public.public_sightings where id=(select id from fixtures where name='confirm')),'moderator fuzzed');
select pg_temp.check_it((select count(*)=0 from public.public_sightings where id=(select id from fixtures where name='private')),'moderator private hidden');
select set_config('request.jwt.claim.sub',(select id::text from actors where name='admin'),true);
select pg_temp.check_it((select latitude=50 and longitude=14 from public.public_sightings where id=(select id from fixtures where name='private')),'admin exact private');
rollback;
select 'Sensitive geoprivacy tests passed; rolled back' as result;
